apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-checkpoints-pv
  labels:
    type: local
    purpose: flink-checkpoints
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/flink-checkpoints"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
