apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-savepoints-pv
  labels:
    type: local
    purpose: flink-savepoints
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/flink-savepoints"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
